name: weixin
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest 
    timeout-minutes: 10  # 设置整个作业的超时时间
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.18'
          cache: 'pip'
      
      - name: Set timezone
        run: |
          sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      
      - name: Install pip packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run weixin script
        timeout-minutes: 8  # 设置单个步骤的超时时间
        run: |
          echo "开始执行脚本..."
          python main.py
        env:
          PYTHONUNBUFFERED: 1  # 确保Python输出不被缓冲
          # 如果脚本需要环境变量，在这里添加
          # WEIXIN_TOKEN: ${{ secrets.WEIXIN_TOKEN }}
